#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home_local/dilawars/nC_projects/Ex3_Morphology_copy/generatedNEURON/x86_64/.libs/libnrnmech.so" "$@"
